workflows:
  example:
    name: Example
    instance_type: mac_mini_m1
    environment:
      groups:
        - shorebird
      flutter: stable
    scripts:
      - name: ðŸ¦ Setup Shorebird
        script: |
          # Install Shorebird
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          # Add Shorebird to PATH
          echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
      - name: ðŸš€ Shorebird Patch
        script: shorebird patch android