name: ask_gemini
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  dash_chat_2: ^0.0.20
  flutter_gemini: ^2.0.3
  image_picker: ^1.0.7

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - shorebird.yaml
  uses-material-design: true

