name: ask_gemini
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  dash_chat_2: ^0.0.20
  flutter_gemini: ^2.0.3
  image_picker: ^1.0.7
  flutter_dotenv: ^5.1.0
  

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  image_path_android: assets/icons/icon1.png
  image_path_ios: assets/icons/icon2.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets:
    - assets/icons/
    - shorebird.yaml
    - .env
  uses-material-design: true

